version: "3.7"

services:
  nexus3:
    image: sonatype/nexus3:latest
    restart: always
    container_name: nexus3
    volumes:
      - /home/dsk/Documents/lab/ci-cd/nexus/nexus3_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd

networks:
  cicd:
    external: true

volumes:
  nexus3_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/nexus/nexus3_data"