version: "3.7"

services:
  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "5000:5000"
    environment:
      DISABLE_IPV6: "true"
    volumes:
      - /home/dsk/Documents/lab/ci-cd/jenkins/nginx/conf/production.json:/app/config/production.json
      - /home/dsk/Documents/lab/ci-cd/jenkins/nginx/nginx_data:/data
      - /home/dsk/Documents/lab/ci-cd/jenkins/nginx/nginx_letsencrypt:/etc/letsencrypt
      - /home/dsk/Documents/lab/ci-cd/jenkins/nginx/nginx_storage:/storage
    networks:
      - cicd

networks:
  cicd:
    external: true

volumes:
  nginx_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/jenkins/nginx/data"
  nginx_letsencrypt:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/jenkins/nginx/letsencrypt"
  nginx_storage:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/jenkins/nginx/storage"