version: "3.7"

services:
  sonarqube:
    image: sonarqube:lts
    restart: always
    container_name: sonarqube
    depends_on:
      - postgres
    environment:
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=devops2021
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonarqube
    volumes:
      - /home/dsk/Documents/lab/ci-cd/sornarqub/sonarqube_conf:/opt/sonarqube/conf
      - /home/dsk/Documents/lab/ci-cd/sornarqub/sonarqube_logs:/opt/sonarqube/logs
      - /home/dsk/Documents/lab/ci-cd/sornarqub/sonarqube_data:/opt/sonarqube/data
      - /home/dsk/Documents/lab/ci-cd/sornarqub/sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - cicd

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - /home/dsk/Documents/lab/ci-cd/sornarqub/postgres_data:/var/lib/postgresql/data
    networks:
      - cicd
    secrets:
      - source: postgres_password
        target: /run/secrets/postgres_password
        mode: 444

secrets:
  postgres_password:
    file: ./secrets/postgres_password

networks:
  cicd:
    external: true

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/sornarqub/devops/postgres_data"
  sonarqube_conf:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/sornarqub/devops/sonarqube_conf"
  sonarqube_logs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/sornarqub/devops/sonarqube_logs"
  sonarqube_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/sornarqub/devops/sonarqube_data"
  sonarqube_extensions:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/sornarqub/devops/sonarqube_extensions"