version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    volumes:
      - /home/dsk/Documents/lab/ci-cd/portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd

networks:
  cicd:
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dsk/Documents/lab/ci-cd/portainer/portainer_data"